### ISSUE TITLE
Todo next gen statistics

### ISSUE THREAD

**Issue by thijsheus** [microhh/microhh#178]
- [ ] refactor and simplify current stats
- [ ] work masks outward
- [ ] port masks to gpu
- [ ] port kernels to gpu:
 - [ ] mean
- [ ] other profiles
 - [ ] path, cover, and other timeseries
 - [ ] tendencies
 - [ ] spectra

**Comment by julietbravo** [comment]
- [ ] Cross-sections of integrals over `x` or `y`.

**Comment by Chiil** [comment]
- [] accumulated fluxes

**Comment by Chiil** [comment]
Important question in 3.0 route is whether we want to allow OpenACC. It could making non-performance critical routines a lot easier. Effectively, this boils down to adopting NVIDIA HPC compiler set as it is as far as I know the only compiler that delivers really fast GPU code for NVIDIA cards

**Comment by thijsheus** [comment]
I dont think there is a need just yet, as porting the CPU kernels to the GPU shouldn't be too crazy. If it turns out that (say) masks are tricky to do, we can reevaluate.

The hope is also to have a stable set of kernels on the CPU first, so that we shouldn't have to do much outside of stat.cu/cxx

**Comment by thijsheus** [comment]
Issues along the way:


- [x] 2d temp files
- [ ] optimize 2d averages (use `reduce_interior` functions; always use doubles for averaging)
- [ ] properly use `pow` function
- [ ] generalize the `grid` and `block` variables
