### ISSUE TITLE
Checklist for integration raytracer

### ISSUE THREAD

**Issue by Chiil** [microhh/microhh#81]
- [ ] Consistent usage of reference and actual `rho`
- [ ] User input for number of photons
- [ ] Proper looping over gas optics in subcolumns to save memory

**Comment by thijsheus** [comment]
it's integrated, so i presume this happened
